// Auto-generated by Supabase CLI — DO NOT EDIT MANUALLY
// Run: npm run types
// Command: supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.ts

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

// Replace this file by running: npm run types
// after connecting your Supabase project
export interface Database {
  public: {
    Tables: {
      travellers: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      invoices:   { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      receipts:   { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      proformas:  { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      quotations: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
    };
    Views: Record<string, never>;
    Functions: {
      next_doc_number: { Args: { doc_key: string }; Returns: string };
      auth_role:       { Args: Record<never, never>; Returns: string };
    };
    Enums: Record<string, never>;
  };
}
