// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/invoices" | "/invoices/[id]" | "/invoices/new" | "/login" | "/proformas" | "/proformas/[id]" | "/quotations" | "/quotations/[id]" | "/quotations/new" | "/receipts" | "/receipts/[id]" | "/receipts/new" | "/settings" | "/travellers" | "/travellers/[id]" | "/travellers/new"
type AppRouteHandlerRoutes = "/api/pdf/invoice/[id]" | "/api/pdf/quotation/[id]" | "/api/pdf/receipt/[id]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/pdf/invoice/[id]": { "id": string; }
  "/api/pdf/quotation/[id]": { "id": string; }
  "/api/pdf/receipt/[id]": { "id": string; }
  "/dashboard": {}
  "/invoices": {}
  "/invoices/[id]": { "id": string; }
  "/invoices/new": {}
  "/login": {}
  "/proformas": {}
  "/proformas/[id]": { "id": string; }
  "/quotations": {}
  "/quotations/[id]": { "id": string; }
  "/quotations/new": {}
  "/receipts": {}
  "/receipts/[id]": { "id": string; }
  "/receipts/new": {}
  "/settings": {}
  "/travellers": {}
  "/travellers/[id]": { "id": string; }
  "/travellers/new": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
